<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Convert Currency</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1bff92e7-b41d-411d-b439-57538c9183bf</testSuiteGuid>
   <testCaseLink>
      <guid>d4d17937-925a-47c8-b4fb-2794c0583736</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/Valid from curr to curr and amount</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>874524fd-8eb6-417b-b2e9-ee4097b8e652</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>845d41e7-7cf8-40e7-a329-0374ed25fd1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b4c82f1-670f-4add-8d64-186f3024a90a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c377c0f-ba2e-4b84-b768-3c1cff902214</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11a07f98-370b-440a-ad06-8a4005ee0bd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/Rate Type</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58a9f4f5-e816-4380-8af0-4491caab8515</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66d4bc9d-ad10-4a39-a9ee-0e831a305e38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cecc3cf-a9e7-4815-bfe7-caa37a770bb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>869a5382-27d6-46a7-8f8d-48de93c73a94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c4e4b6d-5c6e-4ef0-8cc9-8f27cefe6b04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/Rate type Tran type Conversion table ID</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8592e464-71b2-4d7d-9eb0-b3bd27ed91ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc903472-156b-410e-9771-ef9689bb2e6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>372af453-25f7-418b-890c-b45855f0c37f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3ccb57c-bfc2-446f-adc0-80422913fde8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>168f5b8d-f77a-4aa4-88cc-c113af9f3549</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/Fee Flag A</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>493d85cc-e336-49ab-9f57-348d41d7dd50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc926b63-f086-4f88-a150-91dea082eff6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60a222b8-7200-4520-8e53-0cfc56c57c32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce591606-31ad-4028-80b6-9bdd6e993516</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49f32b65-773b-4234-9cef-a5fe707145d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/Fee Flag S</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b734e52-c0ca-4e91-8dbb-e9e758c65d34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>825c72d6-48dd-4f07-919f-bbd629dfcde3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcbef261-a545-4e22-8e3f-c57752b61516</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f3a2c4f-992f-416b-871e-bbf884bbeb5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a35270a4-7eb9-4e70-bcd3-927a58ce38cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/Override Exchange Rate</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77a7aac7-ce6a-439c-95ee-13d1ee42068a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1500bf22-e0c1-4fe4-a799-2ee4b7cf2fe9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7fcc633-9149-468c-99bf-44f0d26a14e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d619365e-9193-4a28-a0db-a8c3b475b497</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b05a799f-0077-4153-a051-1c6481ae7904</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/FromCurr exp- 2 ToCurr Exp -2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f45eb64-916d-4e93-9391-9d12532c11bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56e95988-65cc-444b-bb88-e6fab3cc7813</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6972b2a1-97ba-4989-8dd2-254777831213</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c29fa734-3500-443b-8387-7df87f40e5dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a482a23-3939-4c9b-99ed-074ba6f8bb87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/From Curr exp-2 To curr exp- 0</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6977c984-d518-4951-9c80-f6d5c94bee36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>807f6c11-69b5-4807-8b10-b82a43493203</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72757980-014b-41e0-ba57-0840e422c12e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ad6e38-feb3-4cae-b9b3-4abea39dc690</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6c3c97e-30f1-4106-9c7d-d3c6c11a47af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/From Curr exp-2 To curr exp- 3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cbc9488-8e6d-4e77-bdc5-b805d295e982</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33419319-5824-44c7-995b-542a015bc28f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9abdf626-e8a7-4fb2-b9bf-88c52d10809a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4331809d-ca57-4760-8f42-72198b8f3256</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ad548c1-a531-4395-884f-6f56187488e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/From curr exp-3 To Curr exp -2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84607c71-5c3d-48c6-b171-4923bde785b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89821615-32df-4308-a11d-ec74055e069f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3002cd71-cfa4-440d-b0c1-e111a3081e05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a9dd1cb-67ff-4b63-80d3-470a0a347382</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5206ec53-9d30-4707-9b9a-f0b2ab241bf3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/effective date and time</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52cee399-846d-4ffd-ad79-3a2756b61e18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e6a5bd8-c9a2-402c-8d8a-de9e2fe37055</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5344419f-7d87-4774-a45a-e879b8dbac12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21b2c7d1-b49c-4c6d-9ca1-452ff727d042</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06b7f961-76b2-4676-b379-1a226e39b8a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/From Curr not found</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>906402f7-cef3-40ce-af8e-3302a5f1ced6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eedd4433-185a-4aeb-8c51-220ff8b1ea5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f35cfbd-a409-4885-a785-be0b16e6b33f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>062bec20-8ff7-42f7-a9a4-f6fec55ae829</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6c878fc-a029-46a7-9f45-ab58d6076197</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/Amount equal to zeroes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>037c1990-e0c1-4e1e-98e1-9e7b899332aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91ddb286-cac8-4355-ad3c-19f0979720cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6231dcfa-7c07-4709-bb6a-a7e002bba109</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc367c75-5e0e-4326-b243-24f602f4f2c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b436c544-a535-417e-930e-a68b1498767f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/Points or Fee not found</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c63a28fa-32a5-4feb-b211-73eafdbf9ee2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7abe0581-ef79-4f8d-8d55-62c8fa928217</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>624258e0-1af9-4812-b042-3cc78308b070</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d480a6c4-caec-42e1-9ea8-3a7cf43af03d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd041e0b-748b-4cb0-996e-81eb7de58e73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Convert Currency/From Currency default to USD if spaces</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31691257-528e-49ef-b20e-f0e8066d1509</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6fe98b7-3b94-4767-8d05-153f58420d68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76221b4b-449f-4d1d-a132-317208ccb6b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af0532ed-ea38-4ee1-bd70-46b490189d65</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
