<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Create Combined Statement</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c16670ac-bde1-41b7-826a-d91c2e2b6ee1</testSuiteGuid>
   <testCaseLink>
      <guid>694308b5-3dad-4056-b163-7ccdfd2b5522</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create Combined Statement/Create Combined Statement Post Request Verify Response with valid Values</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bba5deb5-08bc-4ae3-b5b5-f07e0cc6f3e6</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Z-Connect Test Data/Create Combined Statement_TestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>bba5deb5-08bc-4ae3-b5b5-f07e0cc6f3e6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>applicationCd</value>
         <variableId>a15793ad-e057-4b3b-a51d-4ada4c602856</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bba5deb5-08bc-4ae3-b5b5-f07e0cc6f3e6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>statusCd</value>
         <variableId>0711d5bd-c422-4425-a26f-4ec57441f647</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bba5deb5-08bc-4ae3-b5b5-f07e0cc6f3e6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>statusmessage</value>
         <variableId>78c8cf47-5287-462d-a9ae-8be2e2cf7baa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bba5deb5-08bc-4ae3-b5b5-f07e0cc6f3e6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>severity</value>
         <variableId>14dbf657-d4fb-4ce6-b2d6-b3e18ab98736</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6848bd53-482d-4120-90de-c64ed31d9ca6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create Combined Statement/Create Combined Statement Post Request Verify Response with Empty Values</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b4bebcaa-b058-46b4-a6ae-f9c2889003c2</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/Z-Connect Test Data/Create Combined Statement_TestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b4bebcaa-b058-46b4-a6ae-f9c2889003c2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>applicationCd</value>
         <variableId>b790eb9d-c0ab-49b7-b1f8-a3d65597453c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b4bebcaa-b058-46b4-a6ae-f9c2889003c2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>statusCd</value>
         <variableId>b5c945c7-f248-41e1-9f23-016429dfa32e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b4bebcaa-b058-46b4-a6ae-f9c2889003c2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>statusmessage</value>
         <variableId>606d8624-81e1-4d99-9078-0f9f2984f64e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b4bebcaa-b058-46b4-a6ae-f9c2889003c2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>severity</value>
         <variableId>61c69aa9-4134-4b7e-98f0-8a3bffa92044</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c03084f-72c2-4872-b482-580cffe787bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create Combined Statement/Create Combined Statement Post Request Verify Response with Invalid Values</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bef90651-9d68-4b49-b6c3-7e7e9e5745ee</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>3</value>
         </iterationEntity>
         <testDataId>Data Files/Z-Connect Test Data/Create Combined Statement_TestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>bef90651-9d68-4b49-b6c3-7e7e9e5745ee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>errorMessage</value>
         <variableId>28b580fa-2de6-470d-96c6-532bc7a5bdeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bef90651-9d68-4b49-b6c3-7e7e9e5745ee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>errorDetails</value>
         <variableId>89d62c85-4ab4-4767-98d9-40497e58dd8f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
